// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { horneroDbBlock } from "./index";

export const horneroDbBlockSchema = parseBlockSchema(horneroDbBlock);
export const horneroDbCredentialsSchema = parseBlockCredentials(
  horneroDbBlock.id,
  auth,
);
